cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy_dev
  - deploy_prod

init:
  stage: init
  image: node:14.17.1
  script:
    - npm install

deploy_dev:
  image: node:14.17.1
  stage: deploy_dev
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/$DEV_APP_NAME.git HEAD:main
    - echo "Deployed to dev server"
  environment:
    name: dev
    url: https://$DEV_APP_NAME.herokuapp.com/
  only:
    - development

deploy_production:
  image: node:14.17.1
  stage: deploy_prod
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/$APP_NAME.git HEAD:main
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://$APP_NAME.herokuapp.com/
  only:
    - main
